### ISSUE TITLE
throw new Error("Connection failure event: " + eventData.error.toString());

### ISSUE THREAD

**Issue by roger6325** [tasict/homebridge-jci-hitachi-platform#3]
[12/28/2023, 9:48:26[PM] [JciHitachi Platform] Restarting Process...
[12/28/2023, 9:48:27[PM] [JciHitachi Platform] Launched child bridge with PID 27067
[12/28/2023, 9:48:28[PM] Registering platform 'homebridge-jci-hitachi-platform.JciHitachi Platform'
[12/28/2023, 9:48:28[PM] [JciHitachi Platform] Loaded homebridge-jci-hitachi-platform v1.0.10 child bridge successfully
[12/28/2023, 9:48:28[PM] [JciHitachi Platform] Attempting to log into JciHitachiAWSAPI.
[12/28/2023, 9:48:28[PM] Homebridge v1.6.1 (HAP v0.11.1) (JciHitachi Platform) is running on port 57837.
[12/28/2023, 9:48:29[PM] [JciHitachi Platform] You have 7 devices.
[12/28/2023, 9:48:31[PM] [JciHitachi Platform] Host User : Roget,Chou

/homebridge/node_modules/homebridge-jci-hitachi-platform/src/jci-hitachi-aws-api.ts:817
            throw new Error("Connection failure event: " + eventData.error.toString());
                  ^
Error: Connection failure event: Error: libaws-c-mqtt: AWS_ERROR_MQTT5_CONNACK_CONNECTION_REFUSED, Remote endpoint rejected the CONNECT attempt by returning an unsuccessful CONNACK
    at Mqtt5Client.<anonymous> (/homebridge/node_modules/homebridge-jci-hitachi-platform/src/jci-hitachi-aws-api.ts:817:19)
    at Mqtt5Client.emit (node:events:513:28)
    at Mqtt5Client.emit (/homebridge/node_modules/homebridge-jci-hitachi-platform/node_modules/aws-crt/lib/common/event.ts:95:22)
    at /homebridge/node_modules/homebridge-jci-hitachi-platform/node_modules/aws-crt/lib/native/mqtt5.ts:623:20
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
[12/28/2023, 9:48:31[PM] [JciHitachi Platform] Child bridge process ended
[12/28/2023, 9:48:31[PM] [JciHitachi Platform] Process Ended. Code: 1, Signal: null

**Comment by tasict** [comment]
Due to changes in the AWS MQTT authentication protocol, the original process is no longer effective and requires further investigation.

**Comment by tasict** [comment]
Fixed. Please see [commit](https://github.com/tasict/homebridge-jci-hitachi-platform/tree/1d708a4f50392451ef4c0a66229358176228f099)

**Comment by tasict** [comment]
Fixed.

**Comment by roger6325** [comment]
I've tested, the new version works! Thank you for your hard working!!!!
