### ISSUE TITLE
Error: AWS CRT binary not present in any of the following locations

### ISSUE THREAD

**Issue by KoCMoHaBTa** [tasict/homebridge-jci-hitachi-platform#5]
After installing and configured the plugin, then restarted Homebridge and getting the following error:
```
ERROR LOADING PLUGIN homebridge-jci-hitachi-platform:
Error: AWS CRT binary not present in any of the following locations:
        /usr/local/lib/node_modules/homebridge-jci-hitachi-platform/node_modules/aws-crt/dist/bin/linux-arm-glibc/aws-crt-nodejs.node
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-jci-hitachi-platform/node_modules/aws-crt/lib/native/binding.js:88:11)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-jci-hitachi-platform/node_modules/aws-crt/lib/native/auth.ts:15:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
```

And this after several lines of other logs:
```
No plugin was found for the platform "JciHitachi Platform" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

Homebridge v1.8.4 (HAP v0.12.2)

**Comment by MarijoVidovic** [comment]
I encounter same issue, is there any fix or workaround

**Comment by MarijoVidovic** [comment]
@KoCMoHaBTa 

This only supports Asia. I doubt he will ever update it or align it with EU. Waste of time. We should fork it and make EU version

**Comment by tasict** [comment]
@MarijoVidovic 
I live in Taiwan, and Hitachi does not provide an official API. I can only develop this plug-in in Taiwan through the Hitachi official App communication protocol. If you need it, you are of course welcome to Clone and modify this plug-in yourself.
